# Generated by Django 3.2.5 on 2021-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210711_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='bank_amount',
            field=models.IntegerField(default=0),
        ),
    ]
