# Generated by Django 3.2.5 on 2021-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameboard_bank_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='bank_amount',
            field=models.IntegerField(default=5000),
        ),
    ]
