# Generated by Django 3.2.5 on 2021-07-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameplayer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField()),
                ('no_of_players', models.IntegerField(default=0)),
                ('bank_amount', models.IntegerField(default=5000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cell_conf', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameboardmodel'),
        ),
        migrations.DeleteModel(
            name='GameBoard',
        ),
    ]
