# Generated by Django 3.2.5 on 2021-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=models.IntegerField(default=1000),
        ),
    ]
